config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root to: 'pages#index'
  get 'pages/test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :questions do
  	resources :answers
  	post :right
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord

	belongs_to :question

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

	has_many :answers


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
before_action :authenticate_user!

def create
	params[:answer][:question_id] = params[:question_id]
	@answer = Answer.create(answer_params)
  if @answer.save
  else 
    @answer.errors.full_messages.each do |msg|
     @msg = msg
    end  
    flash[:notice] = "#{@msg}"
  end
  redirect_to pages_test_path
end

def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answer.find(params[:id])
    @answer.destroy
    redirect_to pages_test_path
  end
private

	def answer_params
		params.require(:answer).permit(:user_id, :name, :question_id, :ans_ques)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only:[:test]
  def index
  end

  def test
  	@question = Question.all
  	@i=1
  	@res=0
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!
  before_action :set_question, only: [:show,:edit,:update,:destroy]

  def new
		if current_user.admin
  		@question = Question.new
		else
			redirect_to root_path
		end
  end

  def show
      @answers = Answer.where(question_id: @question.id)
      @answer= Answer.new
      respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    if current_user.admin
  	@question = Question.new(questions_params)
    	if @question.save
    		redirect_to root_path
    	else
    		render 'new'
    	end
    end
  end

  def destroy
  	@question.destroy
  	redirect_to root_path
  end

  def edit
  end

  def update
  	@question.update(questions_params)
  	redirect_to root_path
  end


  def right
    @question = Question.find(params[:question_id])
    @flag = false
    @all = params[:user_answer]
    Answer.where(id: @all).each do |ans|
      if ans.ans_ques
        @flag=true
        break
      end
    end
    pp @flag
    respond_to do |format|
      format.js
    end

  end

  private
  	def questions_params
  		params.require(:question).permit(:name)

  	end

  	def set_question
  		@question = Question.find(params[:id])
  	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-airtest">
    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li class="logo">
            <%=link_to root_path do %>
              <img src="/logo.svg" alt="DoIT" height="40px">
            <%end%>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.nil? %>
        <li>
          <%= link_to user_session_path do %>
          <%= t('login') %> <i class="fa fa-sign-in"></i>
          <% end %>
        </li>
       <% else %>
        <% if current_user != nil and current_user.admin %>
          <li>
          <%= link_to new_question_path do%>
          <%= t('Add question') %> <i class="fa fa-plus-circle"></i>
          <% end %>
         </li>
        <% end %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= t('logout') %> <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
      <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
    <title>DoIT</title>
    <%= csrf_meta_tags %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
  <div id="triangle_down"> </div>
    <%= yield %>
    <%= javascript_include_tag 'bootstrap/bootstrap.min.js' %>
  </body>
</html>

app/views/pages/index.html.erb
<%=render "layouts/navbar" %>

<div class="start">
<%= link_to pages_test_path, data:{turbolinks: false} do%>
<button class="button"><font color="white">Start Test</font></button>
<%end%>
</div>

app/views/pages/test.html.erb
<%=render "layouts/navbar" %>
<div class="container">
<div class="tests">
<div class="row">
<section>
<% @question.each do |question| %>
<div class="col-xs-6 col-md-3 col-lg-3 question_block" id="question_<%= question.id %>">
<%= link_to question_path(question.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do %>
<button class="button"><%= 'Test '+ @i.to_s %></button>
	<%end%>
	<% @i+=1 %>
	</div>
<%end%>
</section>
</div>
</div>
<div id="modal-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">



</div>
</div>

app/views/questions/_form.html.erb
<div class="form-group">
<label for="question" class="cols-sm-2 control-label"><p><%= f.label "Question" %></p></label>
 	<div class="cols-sm-10">
	  <div class="input-group">
	  <%= f.text_field :name, placeholder: "Enter your Question", type: "text", class: "form-control"%>
	  	  </div>
	 </div>
</div>
	<div class="form-group">
	  <p><%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button", id: "button" %></p>
	</div>

app/views/questions/_showmodal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel"><center><h1><%= @question.name %></h1></center></h4>
    </div>

    <div class="modal-body">
    <%=form_for :right, url: question_right_path(@question.id), method: :post, html: {class: 'form-signin'}, remote: true do |f|%>
    <div class="container">


      <% @answers.each do |answer|%>
      <div class="row">
      <div class="col-md-9 col-xs-12 col-sm-9  col-lg-6">
        <label>
                <h5><%= radio_button_tag 'user_answer', answer.id %>
                <%= answer.name%></h5>
        </label>
        </div>
        </div>
      <% end %>
     <p> <%=f.submit "Confirm", class: "btn cust-btn", id: "btn-registration", style: "font-size: 20px;letter-spacing: 1px;"%></p>
    <% end %>

    </div>
    </div>
    <% if current_user and current_user.admin %>
      <div class="modal-footer"><center>

          <%= form_for @answer, url:question_answers_path(@question.id) do |f| %>
            <%= f.label "Add Answer"%>
            <p><%= f.text_field :name, placeholder: "Enter your Answer"%>
            <%= f.check_box(:ans_ques)%></p>
          <%= f.submit "Send", class:"d-block btn cust-btn" %>
          <%end%>

        </center>
      </div>
    <%end%>
  </div>
</div>

app/views/questions/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
    <!-- Website Font style -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

<%=render "layouts/navbar" %>
<div class="container">
  <div class="row main">
    <div class="main-login main-center">
<center><%= form_for @question, url: questions_path do |f| %>
	<% if @question.errors.any? %>
	 <% @question.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
	<%= render 'questions/form', f:f%>
<%end%></center>

app/views/questions/right.js.erb
<% if @flag == true %>
	$("#modal-window").hide();
	$(".modal-backdrop").hide();
	$("#question_<%= @question.id %> a button").addClass('green').attr("disabled", true).text('True');
	$("#question_<%= @question.id %> a button font").remove();
<% else %>
	$("#modal-window").hide();
	$(".modal-backdrop").hide();
	$("#question_<%= @question.id %> a button").addClass('red').attr("disabled", true).text('False');
	$("#question_<%= @question.id %> a button font").remove();
<% end %>

app/views/questions/show.html.erb
<div class="start"><h1><font color="red">Відповідь не правильна</font></h1></div>

app/views/questions/show.js.erb
$("#modal-window").html("<%= j render(partial: 'showmodal') %>");

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>